version: 2.1

executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
jobs:
  deploy:
    executor: android-flutter
    steps:
      - checkout
      - run: cd android && flutter build apk

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master